apiVersion: v1
kind: Service
metadata:
  name: nagp-service
spec:
  selector:
    app: nagp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000
